# Application
APP_NAME="Melody Ninja"
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_URL=http://localhost:8000

# Frontend URL
FRONTEND_URL=http://localhost:3000

# Database
DB_CONNECTION=pgsql
DB_HOST=postgres
DB_PORT=5432
DB_DATABASE=melody_ninja
DB_USERNAME=postgres
DB_PASSWORD=secret

# Redis
REDIS_HOST=redis
REDIS_PASSWORD=null
REDIS_PORT=6379

# Mail
MAIL_MAILER=smtp
MAIL_HOST=mailhog
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS="noreply@melody.ninja"
MAIL_FROM_NAME="${APP_NAME}"

# Strava OAuth
STRAVA_CLIENT_ID=
STRAVA_CLIENT_SECRET=
STRAVA_REDIRECT_URI="${APP_URL}/api/auth/strava/callback"

# YouTube Data API
YOUTUBE_API_KEY=

# Firebase Cloud Messaging
FIREBASE_PROJECT_ID=
FIREBASE_PRIVATE_KEY=
FIREBASE_CLIENT_EMAIL=
FIREBASE_DATABASE_URL=

# Anthropic Claude API
ANTHROPIC_API_KEY=

# Queue
QUEUE_CONNECTION=redis

# Session
SESSION_DRIVER=redis
SESSION_LIFETIME=120

# Cache
CACHE_DRIVER=redis

# Logging
LOG_CHANNEL=stack
LOG_LEVEL=debug

# Broadcasting (якщо потрібно)
BROADCAST_DRIVER=log

# Webhooks
STRAVA_WEBHOOK_VERIFY_TOKEN=
STRAVA_WEBHOOK_CLIENT_SECRET=